GET http://localhost:8080/rest1/api/xxx

###
POST http://localhost:8080/rest1/api/xxx
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion
###
POST http://localhost:8080/api/person
Content-Type: application/json

{"fName": "Alan", "lName": "Wake", "phone": "34567890"}